### ISSUE TITLE
Remove country code prefix from county field (EE, LT)

### ISSUE THREAD

**Issue by tormi** [commerceguys/addressing#108]
When using addressing with D8 address module, unnecessary country code prefix is printed with county (administrative area) field in form display, some examples:
- EE: _EE-_
![ee](https://user-images.githubusercontent.com/146800/40966022-03dbde28-68b8-11e8-8c20-799872928900.png)
- LT: _LT-_
![lt](https://user-images.githubusercontent.com/146800/40966029-0b2a4228-68b8-11e8-9418-ded2ff11bc49.png)

I'm not sure whether this issue belongs to addressing package or D8 address module.

**Comment by bojanz** [comment]
This is an address module issue. Please open it there, and then link it so we can close this one.

**Comment by tormi** [comment]
Done, thanks! https://www.drupal.org/project/address/issues/3007148
