### ISSUE TITLE
Possible breaking API change from beta with country list

### ISSUE THREAD

**Issue by wongjn** [commerceguys/addressing#109]
This is in regards to something I spotted with `\CommerceGuys\Addressing\Country\CounryRepository::getList()`:

At least up until v1.0.0-beta3, the method would return an array of country name strings keyed by their country code.:
```php
[
  'AB' => 'Country AB',
  'CD' => 'Country CD',
  ...
]
```
However, the v1.0.0 method now returns an array of country information arrays:
```php
[
  'AB' => [
    ...
  ],
  'CD' => [
    ...
  ],
  ...
]
```

 This is now does not match up with the `@return` signature (`string[]`) in `\CommerceGuys\Addressing\Country\CounryRepositoryInterface` and so I am wondering if this is intentional?

This also has side affects on the Drupal module too.

**Comment by bojanz** [comment]
getList() still returns a regular list. We also have tests that confirm this.

Since you're using the Drupal module, the behavior that you're seeing is probably caused by not running update.php after updating the module (which clears cache and the old cached definitions, whose format changed).
