### ISSUE TITLE
Wrong Brazil Address Order

### ISSUE THREAD

**Issue by carloseachaves** [commerceguys/addressing#112]
Hi,

I'm using the address module for drupal 8 and i think i found a bug in brazil address order. 

I'm looking for this file AddressFormatRepository.php, in a method getDefinitions().  Its seem to me that the format is in the wrong order.

I changed the format order and after that it stayed in the default Brazil address. I'm attaching two files one with the incorrect order and another with correct order.

I would be very happy to contribute with this small improvement.

Correct Order after my change.
<img width="838" alt="correct-order" src="https://user-images.githubusercontent.com/5777058/42741148-32b5d62a-8886-11e8-8aab-d4a540903109.png">

Incorrect Order. Current Code.
<img width="840" alt="incorrect-order" src="https://user-images.githubusercontent.com/5777058/42741149-32d5de2a-8886-11e8-800d-feacb26a173d.png">

**Comment by bojanz** [comment]
Thanks!

You will want to open a bug report at https://github.com/googlei18n/libaddressinput/issues, our dataset is automatically generated from Google's endpoint.

Once they make the change, it will be pulled into this library (and thus the Drupal module too).
