### ISSUE TITLE
Runtime extension of data

### ISSUE THREAD

**Issue by broncha** [commerceguys/addressing#129]
Is there any way we can extend/change the data at runtime, rather than updating library_customizations and generating the resources again?

**Comment by bojanz** [comment]
You can do what Drupal does, extend the relevant repository classes (AddressFormatRepository, CountryRepository, SubdivisionRepository), inject an event dispatcher, dispatch an event from processDefinition or loadDefinitions.

See https://git.drupalcode.org/project/address/blob/8.x-1.x/src/Repository/AddressFormatRepository.php#L38
https://git.drupalcode.org/project/address/blob/8.x-1.x/src/Repository/SubdivisionRepository.php#L53

**Comment by ytsurk** [comment]
This example helped me: https://git.drupalcode.org/project/address/blob/8.x-1.x/tests/modules/address_test/src/EventSubscriber/GreatBritainEventSubscriber.php
