### ISSUE TITLE
Rename Czechia to Czech Republic

### ISSUE THREAD

**Issue by artemkolotilkin** [commerceguys/addressing#134]
Seems like the official name of the country is "Czech Republic", with "Czechia" being a short version. We should probably use an official, full name by default.

**Comment by bojanz** [comment]
That's what CLDR is for. They argue over things like this, and we (and all other vendors) use the results. They said it's Czechia: https://github.com/unicode-org/cldr/blob/10e11a8e45ae9a1aac3919b1252b5cc91c318634/common/main/en.xml#L948
(They tend to prefer shorter versions in general).

You are free to raise that question here: https://unicode-org.atlassian.net/browse/CLDR
If a change is accepted into the next CLDR release, it will show up here.

**Comment by artemkolotilkin** [comment]
Thanks for sharing this! Indeed, "Czechia" is now a recommended name variation for all non-legal context. Recommended by their Ministry of Foreign Affairs. See this ticket for more details https://unicode-org.atlassian.net/browse/CLDR-9958
