### ISSUE TITLE
Construct AddressLine1 from separately the street and number according to country standards

### ISSUE THREAD

**Issue by hacktisch** [commerceguys/addressing#138]
Please provide a means of combining street and number together according to the standards in the country.
I don't know how many variations exist, but for instance:
UK = street_number + street_name
most of europe = street_name + street_number
Russia = street_name + building_number + apartment_number

**Comment by bojanz** [comment]
I'd be happy to evaluate pull requests attempting to do this, but I'm guessing it won't be easy to gather the rules. That's why this library tries to stick to external data sources (CLDR, Google),
