### ISSUE TITLE
Formatted US addresses do not adhere to USPS recommendations. Is that on purpose?

### ISSUE THREAD

**Issue by mehov** [commerceguys/addressing#141]
Hello and thank you for your work!

I tried the [Formatters](https://github.com/commerceguys/addressing#formatters) example, but made it slightly more complex by using the full words, e.g. avenue instead of ave. and suite instead of ste. and all in one line.

I then did `echo($formatter->format($address))` and here's what I have noticed:

- The suite is not moved [*above*](https://pe.usps.com/businessmail101?ViewName=DeliveryAddress) the main address
- In general, the software seems to implement the *Address Line 2* concept, while in fact [it's a common misconception](https://www.serviceobjects.com/blog/why-address-line-2-should-never-be-offered-in-address-forms/) and [USPS itself doesn't use it](https://stackoverflow.com/questions/6619506/im-getting-concatenated-address-line-from-usps-i-want-to-break-it-some-way)
- Nothing is shortened, i.e. it shows suite instead of ste
- The state and zip code is not separated with double space
- The address is not [converted to uppercase](https://pe.usps.com/text/imm/immc1_008.htm)
- Punctuation (commas, dots and the `#`) is not removed

I made sure `withCountryCode('US')` is present.

I read [the backstory](https://drupalcommerce.org/blog/16864/commerce-2x-stories-addressing) where you said the US-centric forms are annoying (and I agree, actually), so I'm wondering if you ignored these intentionally?

**Comment by bojanz** [comment]
This whole library is built around Google's address formats, used by Chrome and Android (and by now, various eCommerce software, from OroCommerce to Drupal Commerce). You can discuss the US address format in https://github.com/google/libaddressinput/issues

Neither Google nor we adjust the address for any specific shipping provider, that would be the job of code that interacts with that service. All ecommerce sites and solutions I've interacted with have had an address line 2, so if there's a trend to remove it, it's a new one.

**Comment by bojanz** [comment]
No further response given, closing.
