### ISSUE TITLE
Field overrides can not be used in an annotation

### ISSUE THREAD

**Issue by Jelle-S** [commerceguys/addressing#149]
AFAIK only primitive types can be created in annotations, not objects / class instances. This means the field overrides can not be described in an annotation, like so:

```
/**
 * @AddressFormatConstraintValidator(fieldOverrides={
 *     "givenName": "hidden",
 *     "familyName": "hidden",
 *     "organization": "hidden",
 * })
 */
```
Or am I missing something?

**Comment by bojanz** [comment]
Quite possible. I've never used validator with annotations.

The workaround would be to create your own constraint which extends the library one, and add your defaults there.

**Comment by bojanz** [comment]
Nothing else we can do, as far as I can tell.
