### ISSUE TITLE
Incorrect ISO codes for Iran

### ISSUE THREAD

**Issue by interDist** [commerceguys/addressing#154]
ISO recently (2020-11-24) rearranged all codes for the provinces of Iran. Since the subdivision data JSON for Iran was last updated in 2018, it now contains wrong data.

In addition, the JSON contains only the English names of the provinces and not their transliterations. Would it be possible to add the transliterated name as well?

**Comment by bojanz** [comment]
You will want to open a bug report at https://github.com/googlei18n/libaddressinput/issues, our dataset is automatically generated from Google's endpoint. Once they make the change, it will be pulled into this library.

If you describe the suggested data changes in the issue you open, we can try to apply them in our library_customizations.php file.

**Comment by bojanz** [comment]
Fixed in 11aac9e5095226b652b910ea82c7c857ab30eebd.
