### ISSUE TITLE
Philippines subdivisions

### ISSUE THREAD

**Issue by interDist** [commerceguys/addressing#155]
During 2019, an array of changes in the provinces in Philippines was introduced. Various provinces were renamed (e.g., Compostela Valley to Davao de Oro). Since the PH.json file was last updated in 2018, it now contains incorrect data.

**Comment by bojanz** [comment]
You will want to open a bug report at https://github.com/googlei18n/libaddressinput/issues, our dataset is automatically generated from Google's endpoint. Once they make the change, it will be pulled into this library.

**Comment by interDist** [comment]
PH-14 was also renamed officially to _Bangsamoro Autonomous Region in Muslim Mindanao_ or Bangsamoro in short, but since the library does not use region names, I removed its mention from the issue description.

These provinces (in addition to Compostela Valley) were also renamed: Mindoro Occidental to “Occidental Mindoro” and Mindoro Oriental to “Oriental Mindoro”  ¯\\\_(ツ)\_/¯

**Comment by bojanz** [comment]
https://www.iso.org/obp/ui/#iso:code:3166:PH still shows Mindoro Occidental  and Mindoro Oriental. Is there another link you are using for your list?

**Comment by interDist** [comment]
Updated the issue for Google's library. Official publications of PH Govt use these two names, e.g. https://psa.gov.ph/classification/psgc/downloads/SUMWEBPROV-SEPT2020-CODED-HUC-FINAL.pdf.
