### ISSUE TITLE
Bahrain (BH) postcode regex incorrect

### ISSUE THREAD

**Issue by BenWalters** [commerceguys/addressing#157]
Hi,

I believe the postcode regex for Bahrain to be incorrect. It is currently `(?:\d|1[0-2])\d{2}` however I've found that postcodes are: 

> Valid post code numbers are 101 to 1216 with gaps in the range. Known as block number (Arabic: رقم المجمع‎) formally. The first digit in NNN format and the first two digits in NNNN format refer to one of the 12 municipalities of the country. PO Box address doesn't need a block number or city name, just the PO Box number followed by the name of the country, Bahrain.

I see this was previously raised though I'm not sure it was resolved. #91

**Comment by BenWalters** [comment]
@bojanz Do you have any thoughts on this?

**Comment by bojanz** [comment]
Addressing just repackages Google data, so you can suggest a new regexp at https://github.com/google/libaddressinput/issues

Once an issue is open there, I can also add a ibrary override on this side, so that the new data is used before Google makes the change on their end.

**Comment by BenWalters** [comment]
Thanks @bojanz  I will get an issue raised there now.

**Comment by BenWalters** [comment]
Issue raised: https://github.com/google/libaddressinput/issues/207
Also I found another source to backup the previous statement: https://en.youbianku.com/Bahrain

**Comment by BenWalters** [comment]
@bojanz  are you able to implement an override? 
The suggested regex is:
`(?:^|\b)(?:1[0-2]|[1-9])\d{2}(?:$|\b)`

**Comment by BenWalters** [comment]
@bojanz are you able to merge the PR and tag a release for this change please?
