### ISSUE TITLE
Class Country is final

### ISSUE THREAD

**Issue by tm1000** [commerceguys/addressing#162]
Great library!

One question why is the Country class marked final? This is not done on Zones or Subdivisons?

https://github.com/commerceguys/addressing/blob/master/src/Country/Country.php

**Comment by bojanz** [comment]
Thanks!

The Country class was merged from commerceguys/intl, which was more strict about its data model. We should be marking Zone and Subdivision final as well.

Is there a reason why this caught your eye?

**Comment by tm1000** [comment]
@bojanz Thanks!

To be honest I sort of hate "final" classes in open source projects because they limit the ability of the community to extend said classes to add custom methods/functions. 

In my specific case I added a function that allows me to know if a country 1) has a state/province 2) what it should be called (a "state" or a "province").

Marking the rest of those as final isnt going to make me rage quite... just makes me grind my teeth, we all have our reasons for using final :-)

Thanks again for the great library, I am still using it just have it being loaded into another class to add that functionality :-)

**Comment by bojanz** [comment]
```
In my specific case I added a function that allows me to know if a country 1) has a state/province 2) what it should be called (a "state" or a "province").
```
FWIW, both of those are methods on an AddressFormat, that you're supposed to use. getAdministrativeAreaType() and  getSubdivisionDepth(), to be precise.

Keeping custom helper logic in custom services tends to allow for easier updates in the future, though I definitely understand the allure of having it all in the same place conceptually.

**Comment by tm1000** [comment]
@bojanz you thought of everything! exactly what I needed thank you so much!!
