### ISSUE TITLE
Random countries not showing locality

### ISSUE THREAD

**Issue by TMWagner** [commerceguys/addressing#168]
### Environment
Running with the following configuration
New (clean install)  Drupal 9.3.6
Address module 8.x-1.10
commerceguys/addressing v1.2.2

### Issue
Some countries show locality... some don't (that should) 
For example

- Italy: yes
- France: no
- Germany: no
- Canada: yes

<img width="380" alt="image" src="https://user-images.githubusercontent.com/5316689/155909446-58f002f3-079a-437c-840b-e373d64cb2c7.png">

**Comment by bojanz** [comment]
Not sure what you're asking. Your screenshot shows a locality (City) being displayed for France.
