### ISSUE TITLE
Turkey has changed their country name

### ISSUE THREAD

**Issue by large64** [commerceguys/addressing#170]
According to [different sources](https://www.bbc.com/news/av/world-europe-60337147) Turkey has changed their country name to "Türkiye". Should change json file(s) accordingly.

**Comment by bojanz** [comment]
That's not our decision to make, we just package CLDR data. Once CLDR makes the change and creates a new release, it is pulled in here. When the Czech Republic was renamed to Czechia this happened within 6 months (since CLDR has releases twice a year).
