### ISSUE TITLE
Call to action: Russia > Russia [terrorist state]

### ISSUE THREAD

**Issue by tormi** [commerceguys/addressing#175]
There's a call to action to Ukrainian and world IT-community out there: support a flashmob [#RussiaIsATerroristState](https://twitter.com/hashtag/RussiaIsATerroristState?src=hashtag_click). Goal  — to change “Russia” for “Russia is a terrorist state” in all possible web portal & online services, where you need to choose language, delivery etc.

Source: https://twitter.com/FedorovMykhailo/status/1556523604099170304

![FZnh91kX0AIyFjF](https://user-images.githubusercontent.com/146800/183458865-dd330e82-9e25-44ee-ae55-ad6fd39b9859.jpeg)

**Comment by josephdickson** [comment]
Though I empathize, making such a change can create issues for downstream projects.

**Comment by s0menickname** [comment]
How is it going to benefit the project?
