### ISSUE TITLE
Fixing Symfony missing type spec messages 

### ISSUE THREAD

**Issue by slashrsm** [commerceguys/addressing#176]
We have a Symfony 6 project where we use `commerceguys/addressing`. When running our test suite we get a bunch of messages like this. 

```
  1x: Method "Symfony\Component\Validator\Constraint::getTargets()" might add "string|array" as a native return type declaration in the future. Do the same in child class "CommerceGuys\Addressing\Validator\Constraints\AddressFormatConstraint" now to avoid errors or add an explicit @return annotation to suppress this message.
    1x in AddressMassageTraitTest::testMassageAddress from App\Tests\Address
```

The solution is to either add native type specs to the functions that are affected or add a `@return` into the doc block. I can prepare the PR, but I am wondering which approach would be preferred? I suspect that native type specs won't play since we have to support PHP 7.3? Or could we drop support for it since it is already EOL?

**Comment by bojanz** [comment]
Let's do the docblock fix so that we can push out a quick release fixing the problem. We said we'd drop PHP7 support in 2.x, making the real fix possible, but I don't know how much time it will take to push out a 2.0 release.
