### ISSUE TITLE
Subdivision data for Ireland is inconsistent with other countries

### ISSUE THREAD

**Issue by damienmckenna** [commerceguys/addressing#182]
Many (most?) countries in the resources directory store their data with an abbreviated version of the subdivision as the index and then the actual subdivision's name stored in the "name" element. For example, the US file defines the following:

    "AL": {
      "name": "Alabama",
      "iso_code": "US-AL",
      "postal_code_pattern": "3[56]"
    },
    "AK": {
      "name": "Alaska",
      "iso_code": "US-AK",
      "postal_code_pattern": "99[5-9]"
    },

This way when the values are used as a selector it uses e.g. "AL" as the key and then the "name" element of "Alabama" can be shown as the human-readable label.

For Ireland it uses the following structure:

    "Co. Carlow": {
      "iso_code": "IE-CW"
    },
    "Co. Cavan": {
      "iso_code": "IE-CN"
    },

This results in the system needing to use e.g. "Co. Carlow" as the key and then also using it as the human-readable label. This is not technically correct as the correct name would be ["County Carlow"](https://en.wikipedia.org/wiki/County_Carlow), and it creates complications for system builders who don't necessary want to store a non-standard string as the selection's value.

### Proposal

Change the data for Ireland to the following:

    "ISOCODEMINUSCOUNTRY": {
      "name": "County Longname",
      "iso_code": "IE-CW"
    },

e.g.:

    "CW": {
      "name": "County Carlow",
      "iso_code": "IE-CW"
    },
    "CN": {
      "name": "County Cavan",
      "iso_code": "IE-CN"
    },

**Comment by bojanz** [comment]
Agreed. We inherited this problem from Google's dataset, but we can add library overrides that ensure ISO codes are used for Ireland instead.

For example, [bojanz/address](https://github.com/bojanz/address) has the following map:
```
		Regions: NewRegionMap(
			"CW", "Co Carlow", "CN", "Co Cavan", "CE", "Co Clare",
			"CO", "Co Cork", "DL", "Co Donegal", "D", "Co Dublin",
			"D1", "Dublin 1", "D2", "Dublin 2", "D3", "Dublin 3",
			"D4", "Dublin 4", "D5", "Dublin 5", "D6", "Dublin 6",
			"D6W", "Dublin 6w", "D7", "Dublin 7", "D8", "Dublin 8",
			"D9", "Dublin 9", "D10", "Dublin 10", "D11", "Dublin 11",
			"D12", "Dublin 12", "D13", "Dublin 13", "D14", "Dublin 14",
			"D15", "Dublin 15", "D16", "Dublin 16", "D17", "Dublin 17",
			"D18", "Dublin 18", "D19", "Dublin 19", "D20", "Dublin 20",
			"D21", "Dublin 21", "D22", "Dublin 22", "D23", "Dublin 23",
			"D24", "Dublin 24", "G", "Co Galway", "KY", "Co Kerry",
			"KE", "Co Kildare", "KK", "Co Kilkenny", "LS", "Co Laois",
			"LM", "Co Leitrim", "LK", "Co Limerick", "LD", "Co Longford",
			"LH", "Co Louth", "MO", "Co Mayo", "MH", "Co Meath",
			"MN", "Co Monaghan", "OY", "Co Offaly", "RN", "Co Roscommon",
			"SO", "Co Sligo", "TA", "Co Tipperary", "WD", "Co Waterford",
			"WH", "Co Westmeath", "WX", "Co Wexford", "WW", "Co Wicklow",
		),
```

**Comment by damienmckenna** [comment]
Hey Bojanz, thanks for the response.

Listing County Dublin as 26 separate items isn't strictly correct either, those should be sub-subdivisions of the main County Dublin rather than top level items; not every system needs to use these, so they should be optional.

I'll put together a PR on Monday.

**Comment by bojanz** [comment]
This is what Google does, I am fine with shrinking the list but not fine with introducing another level of subdivisions for Ireland. It's a PITA in general.

**Comment by damienmckenna** [comment]
FYI we've been examining the data and it seems like it's a general problem system-wide - there's no consistency with how subdivisions are listed. In some cases like the US the key is indexed by the official two letter abbreviation, while Ireland is keyed by a string that does not have any official nature, while Mexico uses conventional names (their post office does not have an official list of abbreviations).

Upgrading a Drupal site from Addressfield results in apparent data loss - editing an entity with an address field that was migrated from D7 will often result in the locality name being blank as the existing data doesn't match what the Address module expects (https://www.drupal.org/project/address/issues/3337070).

When integrating with 3rd party systems this results in further complexity as in many cases what used to work with D7 no longer works with D9.

I do sympathize with you on this problem - you tried to rely on an existing dataset instead of inventing your own. However, Google did you no favor with their bad data.

I think it might be worth considering standardizing on using the "isoids" value from Google's dataset as the keys in these files, and storing the longer Google "keys" value in another field, especially when some of the files don't have "name" values to provide the official name for each subdivision.

**Comment by damienmckenna** [comment]
I don't suppose you know anyone at Google who might like to fix their data? :-)

**Comment by damienmckenna** [comment]
I think a system-wide fix would necessitate a v2 due to the major changes that would be needed.

**Comment by bojanz** [comment]
There is no fixing Google data, it hasn't been updated in a while, and is now just ours.

I am open to doing a v2 with ISO IDs, but there's no doubt that existing Address and Commerce users would see some level of breakage, as dropdowns would be broken/reset on edit. I would need to get a +1 from Commerce maintainers that they're ready to accept such a support burden, I myself haven't touched Drupal in what is now years.

**Comment by damienmckenna** [comment]
I opened #185 for a generic approach to this.
