### ISSUE TITLE
Make subdivision required for Ireland

### ISSUE THREAD

**Issue by damienmckenna** [commerceguys/addressing#189]
In Ireland the subdivision, i.e. the County level, is required as part of an address, therefore it should be required by this library.

**Comment by damienmckenna** [comment]
I opened an issue on the Google project for this: https://github.com/google/libaddressinput/issues/235

**Comment by bojanz** [comment]
@damienmckenna Do you have any links that would back the subdivision  / administrative area being required?

I am going to trust your word on this when it comes to merging the PR, but Google will probably require stronger proof.

https://www.anpost.com/Post-Parcels/Sending/Correct-Address is unclear, but all examples in the dropdown do seem to include the administrative area.
