### ISSUE TITLE
Gather the list of countries that should have the middle name field

### ISSUE THREAD

**Issue by bojanz** [commerceguys/addressing#192]
Ever since we added the additional_name field, meant to be used for middle names and patronymics, it has remained unused.

In a [recent commit](https://github.com/commerceguys/addressing/commit/0e0ab2b7e8c77c4bf60a9b1f662c1847cc978db0) we finally exposed the additional_name in countries such as RU/UA/BY/BG which use patronymics. Next up: middle names.

Unlike patronymics, which are used in a well known list of countries, I have been unable to determine a precise list of countries that expect a middle name field. Enabling it for all countries would be odd as countries like Serbia or Japan have no such concept.

So, let's crowdsource a list here. I am expecting that people would know whether the middle name should be exposed for their own country. Countries we are sure about, based on feature requests:
- US
- NL

What about other English-speaking places such as UK/IE/CA/AU/NZ? Others?

**Comment by ProCycleDev** [comment]
Counterpoint: Trying to change the name fields based on selected country also fails to take into account that people with non english names can live other places.

I'm in favor of doing a Full Name field for the person's name, whatever they want to be addressed by and not enforcing a structure on names. If a site needs to collect a name to call the person by they can use something other than an address for that.

https://blog.prototypr.io/full-name-vs-first-last-name-ux-best-practice-8c2db7178fd1
https://uxmovement.com/forms/why-your-form-only-needs-one-name-field/

**Comment by AndyD328** [comment]
_Not_ NZ please. Most people have middle names but very few use them from day to day, it's pretty much for govt stuff only. Thanks!
I also agree with the single name field/Full Name field if possible. It's legally possible to have a single name in NZ - https://www.drupal.org/u/gold

**Comment by bojanz** [comment]
For the record, here's the history on why we abandoned the "single name" approach in this library and the Drupal integration:
https://www.drupal.org/project/address/issues/2759939
https://github.com/commerceguys/addressing/issues/58

Thanks for the NZ feedback, happy to leave it out by default. This issue is about reasonable defaults, those disagreeing can still alter-in the field.

**Comment by scottsawyer** [comment]
I am not for enabling by default, but I don't have super strong feelings.  I live in the US, but I actually use my middle name as my "primary" name (if you want to play a joke on your kids, give them your first name as their first name).  As long as it's simple to enable / disable, I don't see a reason to change the default behavior.

**Comment by penyaskito** [comment]
Already discussed, but worth a read if interested in the topic: https://www.w3.org/International/questions/qa-personal-names

**Comment by bojanz** [comment]
All existing feedback has indicated that users do not wish to have a middle name field available by default.

So I'm leaving it to custom code (altering the address format repository).

**Comment by Greg-Boggs** [comment]
To clarify, users do wish to provide middle names, and many developers do wish to be able to add middle names on forms. This is not about the defaults. This is about Address library inappropriately disabling the middle name field even though a developer has expressly configured it to be enabled.

This also affects Drupal Commerce: https://drupal.stackexchange.com/questions/9046/drupal-commerce-how-to-add-middle-name-field-to-the-address-pane
