### ISSUE TITLE
Compiling country data hits PHP Fatal error

### ISSUE THREAD

**Issue by damienmckenna** [commerceguys/addressing#193]
Running generate_country_data.php after some recent changes results in the following error:

    PHP Fatal error:  Uncaught TypeError: file_put_json(): Argument #2 ($data) must be of type string, array given, called in scripts/generate_country_data.php on line 64 and defined in scripts/generate_country_data.php:81

**Comment by damienmckenna** [comment]
The script works with the 1.4.2 release, but it was broken by commit d1c90a5ad5d0332c92c30b9d9f072b4eaf0352c0.

**Comment by bojanz** [comment]
Fixed by https://github.com/commerceguys/addressing/commit/5317af4530f8ee21c2a97536628f6850c09e03b3, thanks for the heads up.
