### ISSUE TITLE
Hong Kong administrative areas use long strings as keys

### ISSUE THREAD

**Issue by damienmckenna** [commerceguys/addressing#195]
The 2.x release was to focus on using standard ISO one-to-three character names for administrative areas in each country. I just discovered that the HK.json file still uses long strings instead of the shortened forms.

**Comment by bojanz** [comment]
Which shortened forms are you suggesting?

No conversion was done because there are no ISO codes defined for Hong Kong: https://www.iso.org/obp/ui/#iso:code:3166:HK
