### ISSUE TITLE
PHP Intellisense error Expected type 'CommerceGuys\Addressing\AddressFormat\AddressFormatRepositoryInterface'.

### ISSUE THREAD

**Issue by khanakia** [commerceguys/addressing#197]
I am using the demo example from here https://github.com/commerceguys/addressing#defaultformatter and getting the below error
PHP Intellisense error 
```Expected type 'CommerceGuys\Addressing\AddressFormat\AddressFormatRepositoryInterface'. Found 'CommerceGuys\Addressing\AddressFormat\AddressFormatRepository'.```

![Screenshot 2023-07-12 at 9 04 34 PM](https://github.com/commerceguys/addressing/assets/2174170/33572595-7f6a-40a9-ae00-16bd05c6c637)

**Comment by bojanz** [comment]
I have no clue what this is about. AddressFormatRepository implements AddressFormatRepositoryInterface.
