### ISSUE TITLE
Unrecognized option "origin_country"

### ISSUE THREAD

**Issue by joostvanhoof** [commerceguys/addressing#199]
Great package, thanks for making this OS!

Quick question, if I do this:

```php
echo $formatter->format($address, ['origin_country' => 'FR']);
```

Which is copy pasted from the readme [here](https://github.com/commerceguys/addressing#postallabelformatter), then I get:

`Unrecognized option "origin_country"`

In the `DefaultFormatter` I also don't see any reference to `origin_country`. Was this removed?

**Comment by bojanz** [comment]
Hm, it's definitely there: https://github.com/commerceguys/addressing/blob/master/src/Formatter/PostalLabelFormatter.php#L39

If the example doesn't work, there might be a bug in the validateOptions() logic.

**Comment by bojanz** [comment]
I just copy-pasted the example from the README:
```php

include 'vendor/autoload.php';

use CommerceGuys\Addressing\Address;
use CommerceGuys\Addressing\Formatter\PostalLabelFormatter;
use CommerceGuys\Addressing\AddressFormat\AddressFormatRepository;
use CommerceGuys\Addressing\Country\CountryRepository;
use CommerceGuys\Addressing\Subdivision\SubdivisionRepository;

$addressFormatRepository = new AddressFormatRepository();
$countryRepository = new CountryRepository();
$subdivisionRepository = new SubdivisionRepository();
// Defaults to text rendering. Requires passing the "origin_country"
// (e.g. 'FR') to the constructor or to format().
$formatter = new PostalLabelFormatter($addressFormatRepository, $countryRepository, $subdivisionRepository, ['locale' => 'fr']);

$address = new Address();
$address = $address
    ->withCountryCode('US')
    ->withAdministrativeArea('CA')
    ->withLocality('Mountain View')
    ->withAddressLine1('1098 Alta Ave');

echo $formatter->format($address, ['origin_country' => 'FR']);
```

and it worked fine. Are you perhaps initializing the formatter some other way, through Drupal or another framework?
