### ISSUE TITLE
Kazakhstan address format

### ISSUE THREAD

**Issue by mattarmitage** [commerceguys/addressing#203]
I am using the Address module in Drupal 9 which relies on the formatting in this library. When selecting Kazakhstan as country the format is changed but I do not think it is correct as it puts the postal code first. 
I've done some research and I don't see why the format is set in this order. I see some difference in the order if the address is in cyrillic format, but not identical to what is being enforced, and this shouldn't be a default anyway.
Attached an example of the order it appears in Drupal 9 for Kazakhstan. 
![Screenshot_20231123_170208_Chrome~2.jpg](https://github.com/commerceguys/addressing/assets/14109269/bea9ac41-70cc-43da-96ed-b234b13dd81d)

**Comment by bojanz** [comment]
Indeed, the postal code comes first in the address format:
```
'KZ' => [
    'format' => "%postalCode\n%administrativeArea\n%locality\n%addressLine1\n%addressLine2\n%addressLine3\n%organization\n%familyName %givenName %additionalName",
    'postal_code_pattern' => '\d{6}',
],
```

This is highly unusual, most address formats aren't like that. Looks like we imported it like that from Google's [address data service](https://www.gstatic.com/chrome/autofill/libaddressinput/chromium-i18n/ssl-address/data/KZ).

We can change it to something more sensible, but we need an authoritative source, a kazpost link or something similar

**Comment by bojanz** [comment]
@mattarmitage How does this sound:
```
            'KZ' => [
                'format' => "%familyName %givenName %additionalName\n%organization\n%addressLine1\n%addressLine2\n%addressLine3\n%postalCode, %locality\n%administrativeArea",
                'required_fields' => [
                    'addressLine1', 'locality', 'postalCode',
                ],
                'postal_code_pattern' => '[A-Z0-9]{7}',
            ],
```
It changes the used layout, makes the postalCode required, and uses a format of 7 alphanumeric characters.

**Comment by mattarmitage** [comment]
Well. The problem is that many places in Kazakhstan still use the old 6
digit numerical postcode. So that may cause problems.
It apparently takes a while for things to happen in Kazakhstan.

**Comment by bojanz** [comment]
Okay, let's go with `\d{5}|[A-Z0-9]{7}` as the regexp then, to support both.

I've also edited my comment above to ask about the regions, please let me know.

**Comment by mattarmitage** [comment]
The regions are beyond my knowledge! They would be good additions though.

**Comment by mattarmitage** [comment]
I spoke with some Kazakhs and they said the weird format was a soviet Russian thing and it has been standardised now to match global standards but basically everyone uses all kinds of formats there. 
But officially it is the same as western format.

**Comment by bojanz** [comment]
Great, pushed a commit that reworks the address format.

I am still waiting on feedback regarding the region names, once I have that I will commit the regions too and report back here.

**Comment by bojanz** [comment]
Opened https://github.com/commerceguys/addressing/issues/204 to track adding the regions.
