### ISSUE TITLE
Singapore lacks city/locality field.

### ISSUE THREAD

**Issue by MichelleCox** [commerceguys/addressing#206]
When choosing Singapore for the country, there is only a place for street address, not city/locality. From what I've found on Google, it does not have states but it does have cities. It would be good to have that field available.

**Comment by bojanz** [comment]
Thank you for reporting this.

UPU confirms the need for a locality field: https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/sgpEn.pdf
(examples with a town name)

**Comment by bojanz** [comment]
Added a required locality field with the label "City", which defaults to "Singapore" (as allowed by #209 )
