### ISSUE TITLE
$addressLine2 never on form

### ISSUE THREAD

**Issue by dnagirl** [commerceguys/addressing#21]
Although `$addressLine2` is a property of `Address`, there is no field-mapping constant available from the `AddressFormatInterface`. So far as I can determine, this means that addressLine2 will never appear in any address form. 

Is this an oversight? Or is there some other way that addressLine2 should be added to an address form?

**Comment by bojanz** [comment]
Just an oversight, improving the address form is on my todo list for the next few days.

**Comment by bojanz** [comment]
Fixed in 850c2aa6dc0a0bdce49a0c95c2c0522dc932fb2c
