### ISSUE TITLE
How to validate a address?

### ISSUE THREAD

**Issue by joaoeduardo** [commerceguys/addressing#22]
Hi! I was searching for PHP Packages for my projects when I found this. This package is amazing. But I cant understand how to validate an address. The README.md speaks little about it. I tryed look the code, but no success. Can you show me an example, or update the README.md? Thanks.

**Comment by bojanz** [comment]
The validator works together with [symfony/validator](https://github.com/symfony/validator), so your usage depends on the way your framework/project is integrating symfony/validator. You can view the validator README for some usage examples.

So, working from scratch, it would look something like this:
```php
use CommerceGuys\Addressing\Model\Address;
use CommerceGuys\Addressing\Validator\Constraints\AddressFormat;
use Symfony\Component\Validator\Validation;

$address = new Address;
$address->setCountryCode('FR');
$address->setLocality('Paris');

$validator = Validation::createValidator();
$violations = $validator->validateValue($address, new AddressFormat());
``
This validates the address fields, but you'd want to validate the country code first, and stop there if it's empty or invalid. One such example can be seen in https://github.com/commerceguys/addressing/commit/743b60fae11cb4622d33462d69ac62628aca569e
(Removed to allow people to use other ways of configuring validators, for example yaml or xml)

**Comment by AgnaldoJaws** [comment]
Can you add me??  https://www.facebook.com/agnaldobernado   

     Em Quarta-feira, 21 de Janeiro de 2015 15:45, Bojan Zivanovic <notifications@github.com> escreveu:
   

 The validator works together with symfony/validator, so your usage depends on the way your framework/project is integrating symfony/validator. You can view the validator README for some usage examples.So, working from scratch, it would look something like this:use CommerceGuys\Addressing\Model\Address;
use CommerceGuys\Addressing\Validator\Constraints\AddressFormat;
use Symfony\Component\Validator\Validation;

$address = new Address;
$address->setCountryCode('FR');
$address->setLocality('Paris');

$validator = Validation::createValidator();
$violations = $validator->validateValue($address, new AddressFormat());
``
This validates the address fields, but you'd want to validate the country code first, and stop there if it's empty or invalid. One such example can be seen in https://github.com/commerceguys/addressing/commit/743b60fae11cb4622d33462d69ac62628aca569e
(Removed to allow people to use other ways of configuring validators, for example yaml or xml)—

**Comment by joaoeduardo** [comment]
I was doing a similar thing, but validation fails with a valid address. Am I forgetting something?

```php
 $address = new Address();
 $address->setCountryCode('BR');
 $address->setAdministrativeArea('BR-SP');
 $address->setLocality('Rio Grande da Serra');
 $address->setAddressLine1('Rua Guilherme Pinto Monteiro');
 $address->setAddressLine2('Centro');
 $address->setPostalCode('09450000');

 $validator = Validation::createValidator();
 $violations = $validator->validateValue($address, new AddressFormat());
```

It tells that the "locality" argument is invalid.

**Comment by bojanz** [comment]
Brazil has predefined localities, so you need to specify the subdivison id instead.
According to https://github.com/commerceguys/addressing/blob/master/resources/subdivision/BR-SP.json the id for "Rio Grande da Serra" is "BR-SP-76c67e".

You can look at the AddressFormatValidatorTest to see other usage examples.

**Comment by joaoeduardo** [comment]
Thank you! I only looked at US address. I didn't see the example with a chinese address. Sorry.

**Comment by joaoeduardo** [comment]
Can I find locality name with the subdivison id?

**Comment by bojanz** [comment]
Yes, load the subdivision object (from the repository or the data provider) and call $subdivision->getName().

**Comment by bojanz** [comment]
I've updated the README.
