### ISSUE TITLE
Suggestion: Make it easier to use data client side

### ISSUE THREAD

**Issue by karptonite** [commerceguys/addressing#26]
It would be useful for me (and maybe others) if there was an easy way to turn an AddressFormat object and perhaps an array of Subdivision objects into a format that would be easily usable for a client side library like Angular. Perhaps some method/class that converts this information to JSON, so that forms that are being generated and updated by js on the client side can still take advantage of the power of the addressing library. (Of course, for validation purposes, the library could still be used server side). 

I know that the formats and subdivisions are already stored in JSON, but going through the repositories seems more appropriate than digging into the data stores (which could change with time) directly.

**Comment by bojanz** [comment]
It makes sense. However, I don't see much work for the library to do, all you basically need is an API endpoint that takes a country code, and returns the address format and subdivisions in json?

I know each framework / group of developers has their favorite serializer that they use to turn a collection of objects into json ([Fractal](http://fractal.thephpleague.com/simple-example/), [Symfony Serializer](http://symfony.com/doc/current/components/serializer.html)...), there's no need for me to enforce a specific convention there?

**Comment by karptonite** [comment]
Yeah, you are probably right on that. The main change I was thinking of was to make the AddressFormat (etc) classes JsonSerializable, so that json_encode could be used directly, but I guess it isn't necessary--I'll just use one of the other libraries.

**Comment by bojanz** [comment]
I must admit I've completely missed the existence of JsonSerializable. 

I see Eloquent implements it by default, but Doctrine doesn't. There's an open feature request for Symfony Serializer, but not for Fractal. Either others are just as ignorant as me, or I'm missing some big limitation.

I'm open to a PR that adds JsonSerializable to AddressFormat and Subdivision. Of course, my assumption is that subdivision children wouldn't be returned (they are lazy loaded by the model usually).

**Comment by karptonite** [comment]
Eh, I don't think it is necessary. The Symfony Serializer did the job for me, probably better than making it JsonSerializable would have.
