### ISSUE TITLE
Have getUsedFields return the fields in the order they are used?

### ISSUE THREAD

**Issue by karptonite** [commerceguys/addressing#27]
Do you think it is worth having `FormatStringTrait::getUsedFields()` return the fields in the order they are actually used?  The use case I have in mind is when presenting a form to a user to enter an address, you may want to show the fields in the correct order, but with each field on its own line. It would be easy to just use the grouped fields for that purpose, but the used fields array seems like the more appropriate data source if you don't actually want to group them.

**Comment by bojanz** [comment]
It would require more complex processing in getUsedFields(). The idea for that method was to be able to answer the question "is this field used or not", getGroupedFields() is the one that's meant to be used for laying out fields, even if there's a decision to not group fields per row (which doesn't make much sense, to be honest?)
