### ISSUE TITLE
Confusion over locale for PostalLabelFormatter

### ISSUE THREAD

**Issue by karptonite** [commerceguys/addressing#29]
I discussed this briefly with @bojanz on Twitter, but I'm still a bit confused about the role of the locale (third argument of the constructor) in the postal label formatter.

In particular, it seems to me to be serving two purposes: one relates to the ordering of the address elements and the translation of the subdivisions, which would be relevant when the item arrives in the destination country. So if someone from China orders something from France, and enters the address in Chinese, the locale (and ordering and subdivisions) would be for the Chinese locale.

However, locale also determines the name of the country in the postal label. So for our example above again, the formatter would be instantiates with origin country "FR" and locale "zh", and thus would have the destination country in Chinese and English, but NOT French. The Universal Postal Union recommendations that you reference suggest that the country be named preferable in the language of the dispatching country, which may not match the locale.

Does this seem like a problem, or am I confused by how locale is intended to be used?

**Comment by bojanz** [comment]
Yes, there's potential confusion.

The assumption here is that the PostalLabelFormatter will be initialized with the locale of the origin country, but it's not enforced. So If mail is being sent from France, it's assumed that the locale will be "fr" as well.

**Comment by karptonite** [comment]
There was an issue that the formatter was getting the format based on the locale of the formatter rather than the locale of the address (which is necessary for correctly rendering the address as entered). It was not possible to correctly format an address written in Japanese, but shipped from France before the changes, I believe. The attached pull request should fix this, but I'm not sure this is the way you'd want to address this issue.

**Comment by bojanz** [comment]
"t seems to me that the locale of the PostalLabelFormatter could be omitted altogether if we could determine the local locale of a country from the country code"
There's no country -> locale mapping, and some countries would have more than one (Switzerland, Canada, etc). So that's not feasible.

The PR seems sensible, I'll give it a thought.

**Comment by karptonite** [comment]
Thanks!
While there is no one-to-one mapping of country-> locale, it might make sense when no locale is passed into the PostalLabelFormatter to use the default locale for a country from the address format definition. The main purpose of the locale for the PostalLabelFormatter will be to make sure that the destination country appears in a local language--as long as it is one of the languages from a country, that should be better than nothing for the purposes of routing the mail.
