### ISSUE TITLE
Addresses and countries validate with empty countries

### ISSUE THREAD

**Issue by karptonite** [commerceguys/addressing#32]
Is it intentional that the country validator returns no violation with an empty or null country?

**Comment by bojanz** [comment]
The address is assumed to be empty if no country has been provided, turning off all validation.

This is the behavior we had previously in Drupal, and it's the same behavior the Country Validator has in symfony/validator. It's assumed that you'd either add a separate required rule for the country, or provide a "None" option which hides all other fields.

**Comment by karptonite** [comment]
OK--just surprised me.
