### ISSUE TITLE
Form field label translations?

### ISSUE THREAD

**Issue by sandermarechal** [commerceguys/addressing#44]
Could you add support for translating form field labels? The address form itself works great but all labels are always displayed in English. I don't know which translation keys I should translate for all the possible form fields.

**Comment by bojanz** [comment]
That can't be done in the library itself, it needs to be done on the application / bundle level.

So a symfony bundle could rely on symfony's translation component and provide yaml files with the strings.

**Comment by sandermarechal** [comment]
Yes, I understand. But this library could use proper key IDs instead of plain language strings (e.g. 'address.city' instead of 'City') and document what all possible translation keys are.

You could even opt to provide translations in XLIFF format in the `resources` directory. XLIFF is an international standard and is framework independent. No need to load these files, just provide them as part of the package so that developers can load them themselves.

**Comment by dnagirl** [comment]
This would be awesome!

**Comment by bojanz** [comment]
Since then the form integration was removed, and a new one is being built in #66. I'll add a note to that issue.
