### ISSUE TITLE
CountryRepository; The path to the country definitions ($definitionPath) missing

### ISSUE THREAD

**Issue by inikoo** [commerceguys/addressing#50]
Hi,

class CountryRepository  in CommerceGuys\Addressing\Repository
The path to the country definitions ($definitionPath) missing,  so it can be passthrough to
\CommerceGuys\Intl\Country\CountryRepository if necesary

**Comment by bojanz** [comment]
It doesn't need to. The intl CountryRepository provides its own definition path, and allows an override only for test purposes. The point of the addressing class is to use the intl class as-is.
