### ISSUE TITLE
Set different fields in different form

### ISSUE THREAD

**Issue by vikey89** [commerceguys/addressing#55]
Hello guys I'm using this library in a project Symfony 3.0.
I have the need to set different fields in different form.

eg:
I have a form that needs fields: Country, Administrative Area, Locality, Postal code, Address line 1 
and another form that should only have Country, Administrative area.

How can I do?

Thanks.

**Comment by bojanz** [comment]
The current form element needs to be rewritten completely. That's one of the features it should have (being able to select which fields are used). Send a PR if you end up doing it :)

**Comment by bojanz** [comment]
To be continued in #66.
