### ISSUE TITLE
Validation example in readme needs updating?

### ISSUE THREAD

**Issue by torkiljohnsen** [commerceguys/addressing#56]
The validation example in the readme looks a lot different from the code in the tests. Method `validateValue()` for instance was deprecated in symfony/validator in version 2.5.

When using the approach from the tests, I ran across this error when trying to validate without first setting a `$context`:

```
FatalThrowableError in AddressFormatValidator.php line 212:

Call to undefined method CommerceGuys\Addressing\Validator\Constraints\AddressFormatValidator::buildViolation()
```

**Comment by bojanz** [comment]
Updated the example, replaced validateValue() with validate(), works fine in https://github.com/commerceguys/addressing/blob/master/scripts/validate_postalcode_patterns.php
