### ISSUE TITLE
Missing US states

### ISSUE THREAD

**Issue by jgrossi** [commerceguys/addressing#59]
Hey,

First thanks for the project. It's amazing. 

I'm writing some unit tests in my local app using your package. Everything is working for others countries like Brazil, for example, but I cannot get any city from any US state, like Colorado, for example.

I was checking the `resources/subdivisions` folder and I could find only a `US.json` file, not a `US-XX.json` one.

Is that right? Are the US states `.json` files really missing?

Thanks for any support. Best regards.

**Comment by bojanz** [comment]
Correct, they are not provided. We only predefine what the countries themselves predefine, USPS does not maintain a list of all US cities (AFAIK). You could try creating such a list, but I'm afraid it would always be incomplete, requiring you to create some kind of "select or type in your own" widget.

**Comment by jgrossi** [comment]
Hi @bojanz! Thank you so much for the support. I really appreciate that.
