### ISSUE TITLE
Incorrect regex pattern for México subdivision

### ISSUE THREAD

**Issue by michfuer** [commerceguys/addressing#70]
I have an address with a postal code in the México (MEX) subdivision and it's failing validation.

The postal code is '03400' and appears accurate according to Wikipedia https://en.wikipedia.org/wiki/List_of_postal_codes_in_Mexico#0xxxx-1xxxx:_Mexican_Federal_District_.28M.C3.A9xico.2C_D.F..29

One strangeness I noticed was that it passes for the $fullPattern match in AddressFormatValidator::validatePostalCode(), but fails the $startPattern match. I would expect it to get validated against one or the other.

The existing pattern is "5[0-7]". In MX.json I set it to "[0-1][0-9]" and it resolved my issue.

It looks like the update should happen further upstream in library_customizations.php or the generate.php script if it is in fact the wrong regex pattern.

**Comment by bojanz** [comment]
Here's our data: 
https://github.com/commerceguys/addressing/blob/master/resources/subdivision/MX.json

You appear to have mixed up the MEX and "D.F." subdivisions. For MEX the pattern is "5[0-7]" and for "D.F." the pattern is "0|1[0-6]", which matches the Wikipedia link you gave.

**Comment by michfuer** [comment]
I think you're spot on! I've either got a wrong postal code, or the wrong province in Mexico.

addressing library cleaning up source data, one address at a time :)
