### ISSUE TITLE
How to add subdivisions for HR

### ISSUE THREAD

**Issue by msajko** [commerceguys/addressing#71]
/resources/subdivisions/HR.json
`{
	"country_code": "HR",
	"subdivisions": {
		"1": {
			"name": "Zagrebačka",
			"iso_code": "HR-01",
			"postal_code_prefix":"10"
		},
		"21": {
			"name": "Grad Zagreb",
			"iso_code": "HR-21",
			"postal_code_prefix": "10"
		},
		"2": {
			"name": "Krapinsko-Zagorska",
			"iso_code": "HR-02",
			"postal_code_prefix": "49"
		},
		"3": {
			"name": "Sisačko-Moslavačka",
			"iso_code": "HR-03",
			"postal_code_prefix": "44"
		},
		"4": {
			"name": "Karlovačka",
			"iso_code": "HR-04",
			"postal_code_prefix": "47"
		},
		"5": {
			"name": "Varaždinska",
			"iso_code": "HR-05",
			"postal_code_prefix": "42"
		},
		"6": {
			"name": "Koprivničko-Križevačka",
			"iso_code": "HR-06",
			"postal_code_prefix": "48"
		},
		"7": {
			"name": "Bjelovarsko-Bilogorska",
			"iso_code": "HR-07",
			"postal_code_prefix": "43"
		},
		"8": {
			"name": "Primorsko-Goranska",
			"iso_code": "HR-08",
			"postal_code_prefix": "51"
		},
		"9": {
			"name": "Ličko-Senjska",
			"iso_code": "HR-09",
			"postal_code_prefix": "53"
		},
		"10": {
			"name": "Virovitičko-Podravska",
			"iso_code": "HR-10",
			"postal_code_prefix": "33"
		},
		"11": {
			"name": "Požeško-Slavonska",
			"iso_code": "HR-11",
			"postal_code_prefix": "34"
		},
		"12": {
			"name": "Brodsko-Posavska",
			"iso_code": "HR-12",
			"postal_code_prefix": "35"
		},
		"13": {
			"name": "Zadarska",
			"iso_code": "HR-13",
			"postal_code_prefix": "23"
		},
		"14": {
			"name": "Osječko-Baranjska",
			"iso_code": "HR-14",
			"postal_code_prefix": "31"
		},
		"15": {
			"name": "Šibensko-Kninska",
			"iso_code": "HR-15",
			"postal_code_prefix": "22"
		},
		"16": {
			"name": "Vukovarsko-Srijemska",
			"iso_code": "HR-16",
			"postal_code_prefix": "32"
		},
		"17": {
			"name": "Splitsko-Dalmatinska",
			"iso_code": "HR-17",
			"postal_code_prefix": "21"
		},
		"18": {
			"name": "Istarska",
			"iso_code": "HR-18",
			"postal_code_prefix": "52"
		},
		"19": {
			"name": "Dubrovačko-Neretvanska",
			"iso_code": "HR-19",
			"postal_code_prefix": "20"
		},
		"20": {
			"name": "Međimurska",
			"iso_code": "HR-20",
			"postal_code_prefix": "40"
		}
	}
}`

**Comment by bojanz** [comment]
Our dataset is automatically derived from Google's dataset, so we can't patch anything in resources/.
Instead you'd need to add the data to the library_customizations.php file so that it's automatically included on next generation.

However, Google seems to think that Croatia doesn't use administrative areas for addressing (people don't write them on mailing labels, etc). Can you confirm that?
If that's true, then this subdivision list is out of scope for this library (we don't include data that's not used for addressing, cause that's what Google does, and we don't have the resources to do it ourselves).

**Comment by msajko** [comment]
True, Croatia doesn't use administrative areas for addressing.
We have add custom fields for subdivision so I'll close this issue.
