### ISSUE TITLE
Guam (GU) does not have administrativeArea

### ISSUE THREAD

**Issue by josephzidell** [commerceguys/addressing#72]
Guam (GU) does not have administrative areas, or states. This is causing issues. Can it be removed and not marked as required? [Wikipedia](https://en.wikipedia.org/wiki/List_of_populated_places_in_Guam)

I can provide a PR.

**Comment by josephzidell** [comment]
If I submit a PR for `library_customizations.php`, will it get accepted?

**Comment by bojanz** [comment]
Yes. You should also check the formats of other US territories, see if they have the same problem. We'll want to report this to Google at https://github.com/googlei18n/libaddressinput/issues

**Comment by josephzidell** [comment]
This was the only issue with US territories.

https://github.com/googlei18n/libaddressinput/issues/115

**Comment by bojanz** [comment]
Great, thank you for following up. Let's add the customization then.

**Comment by josephzidell** [comment]
@bojanz Can you merge this please?
