### ISSUE TITLE
Address with country code "SG" (Singapore) doesn't validate

### ISSUE THREAD

**Issue by stefantalen** [commerceguys/addressing#85]
Not sure why an address with country code "SG" isn't validating. I added it as a test to find out what happens:

```php
// tests/Validator/Constraints/AddressFormatValidatorConstraint
public function testSingapore()
{
    $address = new Address();
    $address = $address
        ->withCountryCode('SG')
        ->withLocality('Singapore')
        ->withPostalCode('79903')
        ->withAddressLine1('10 Anson Road#22-09, Internat.Plaza')
    ;

    $this->validator->validate($address, $this->constraint);
    $this->assertNoViolation();
}
```

If I comment out `->withCountryCode('SG')` the validation passes.

I'm using the library in a Symfony 3.3 project and checked if the country code may be invalid, but it shows up in the Symfony Intl region data sets.

When adding the country code to `CommerceGuys\Addressing\Tests\Validator\Constraints\CountryValidatorTest:getValidCountries()` it validates so I guess it has to do with the AddressFormat

**Comment by stefantalen** [comment]
Got it pinned down to the address_format for SG which has a hardcoded "SINGAPORE" as locality.

If I change this:
```json
{
	"locale": "und",
	"format": "%recipient\n%organization\n%addressLine1\n%addressLine2\nSINGAPORE %postalCode",
	"required_fields": [
		"recipient",
		"addressLine1",
		"postalCode"
	],
	"uppercase_fields": [
		"locality"
	],
	"postal_code_type": "postal",
	"postal_code_pattern": "\\d{6}"
}
```
To this:
```json
{
	"locale": "und",
	"format": "%recipient\n%organization\n%addressLine1\n%addressLine2\n%locality %postalCode",
	"required_fields": [
		"recipient",
		"addressLine1",
		"postalCode"
	],
	"uppercase_fields": [
		"locality"
	],
	"locality_type": "city",
	"postal_code_type": "postal",
	"postal_code_pattern": "\\d{6}"
}
```

The validation then works when adding a recipient (for the test, don't need it for my case).

Is there any reason for the locality being hardcoded in the format? Right now I can't save the locality because of this validation.

**Comment by bojanz** [comment]
SINGAPORE is just there when formatting an address for display, it doesn't hardcode the value in the database.

The address format is saying that there's no locality field at all, which makes sense to me, since there can always be only 1 option. The validator doesn't let you fill in unused fields.

You can open an issue on https://github.com/googlei18n/libaddressinput/issues to argue about including a locality field for Singapore in Google's dataset (which is automatically pulled down into the library).

**Comment by bojanz** [comment]
Now that we no longer depend on Google, we changed this decision in https://github.com/commerceguys/addressing/issues/206
