### ISSUE TITLE
Unexpected '?' in ArrayCollection.php

### ISSUE THREAD

**Issue by asacolips** [commerceguys/addressing#86]
On PHP 5.6, I receive the following error when using the library as part of Drupal's [Address](https://www.drupal.org/project/address) module:

> Parse error: syntax error, unexpected '?' in /var/www/public/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php on line 240

This appears to be due to the Doctrine project [dropping support for PHP 5.6 and 7.0](http://www.doctrine-project.org/2017/07/25/php-7.1-requirement-and-composer.html). Specifically, it appears that collections now uses the `??` operator:

```
/**
 * {@inheritDoc}
 */
public function get($key)
{
  return $this->elements[$key] ?? null;
}
```

**Comment by mglaman** [comment]
In your composer.json try adding the following to your config

```
        "platform": {
            "php": "5.6"
        }
```

Example:

```
    "config": {
        "bin-dir": "bin",
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "platform": {
            "php": "5.6"
        }
    },
```

Can happen if local PHP is 7+ but remote is different.

**Comment by asacolips** [comment]
I did manage to resolve it using that option shortly after posting, but it's still something that isn't particularly clear unless you're familiar with the option or with Doctrine's project release notes. I don't think it's worth changing the composer.json here, but it would definitely be helpful to cover the potential issue and fix in the readme.

**Comment by mglaman** [comment]
There's not much we can do. Composer checks the current platform and version constraints. The issue comes from generating a .lock file on an environment which does not match the deployment environment.

This bit me as well. But there's not much we can do. Glad it is fixed up.
