### ISSUE TITLE
Add phone field

### ISSUE THREAD

**Issue by webprogrammierer** [commerceguys/addressing#87]
How can I add a phone field to the address field?

**Comment by bojanz** [comment]
This library has nothing to do with phone numbers, it handles addresses only.
Phone numbers are generally added a level above the address (parent entity object)

**Comment by webprogrammierer** [comment]
And how and where can I add a phone number field a level above? (Commerce on Drupal 8).
Thank you.

**Comment by webprogrammierer** [comment]
Here is the correct answer:
https://www.drupal.org/node/2904884

Thank you for your great help!
