### ISSUE TITLE
Add US Military State Codes

### ISSUE THREAD

**Issue by mattwebdev** [commerceguys/addressing#90]
my client needs to ship to military zip codes.
here is the formatting required (page 2) https://www.irs.gov/pub/irs-utl/zip%20code%20and%20state%20abbreviations.pdf

**Comment by bojanz** [comment]
You will want to open a bug report at https://github.com/googlei18n/libaddressinput/issues, our dataset is automatically generated from Google's endpoint.

**Comment by amagrude** [comment]
This has been resolved. The AA, AE, AP state codes for APO addresses are in both Google's and your dataset now and match the referenced IRS document.

This issue can be closed.
