### ISSUE TITLE
Postal code regex for Bahrain (BH) is wrong

### ISSUE THREAD

**Issue by tinnerdxp** [commerceguys/addressing#91]
Postal codes in Bahrain also known as "Block numbers", are usually 4 digits, however the regex tries to match against 3 characters first, causing the check:
```
            preg_match('/' . $fullPattern . '/i', $postalCode, $matches);
            if (!isset($matches[0]) || $matches[0] != $postalCode) {
                $this->addViolation(AddressField::POSTAL_CODE, $constraint->invalidMessage, $postalCode, $addressFormat);

                return;
            }
```
to trigger the addViolation() call
the regex should be changed to something allowing more explicit matching, example:
^(?:1[0-2]|\d)\d{2}$

**Comment by tinnerdxp** [comment]
Bear in mind the above postcode is not best for it - as it must only match numbers between 199-1299

**Comment by bojanz** [comment]
The current pattern is: 'postal_code_pattern' => '(?:\d|1[0-2])\d{2}',
Which means that the problem is solved. Reopen if I'm wrong :)

**Comment by tinnerdxp** [comment]
Thanks. I don't work for the company who has the address details any more - so can't confirm or deny unfortunately. But thanks anyway.
