### ISSUE TITLE
Convert administrative area to Abbreviated form

### ISSUE THREAD

**Issue by chorton** [commerceguys/addressing#93]
Hello,

I have a form where users can enter in a state / province.  Is it possible for the library to take what was provided and determine the abbreviated form of that state / province so I can pass that into the address formatter?

Simple Example.  The following fails because the user provided Arizona instead of AZ.  I'd like to be able to perform a lookup to get AZ from whatever they provided.

[...]
```
$stateProvince = 'Arizona';
$city = 'Chandler';
$postalCode = '85286';
$givenName = 'my first name';
$familyName = 'my last name';
$address = $address->withAdministrativeArea($stateProvince)
    ->withLocality($city)
    ->withAddressLine1($streetAddress)
    ->withPostalCode($postalCode)
    ->withGivenName($givenName)
    ->withFamilyName($familyName);
```
[...]

**Comment by stefantalen** [comment]
Why not use a `<select>` in your form in which you've mapped the states with the correct abbreviation?

`<option value="AZ">Arizona</option>`

**Comment by bojanz** [comment]
You can use SubdivisionRepository get a list of subdivisions and try to find a matching one that way. Or what stefantalen told you.
