### ISSUE TITLE
Remove the postal code prefix for Switzerland

### ISSUE THREAD

**Issue by ChristophWolf** [commerceguys/addressing#96]
In Switzerland (and I think in many other countries) It is no longer allowed to print the receipt country as ISO-Code before postal code (e.g CH-8005 Zurich). The Country should only be written under the postal code line.
e.g. 
Max Sample
Sample Street
1234 Sample City
SWITZERLAND

**Comment by bojanz** [comment]
We no longer follow Google's dataset, so let's make our own decision.

I don't see any proof that the postal code prefix is still used on:
https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/cheEn.pdf
https://www.royalmail.com/sending/international/country-guides/switzerland

So let's remove it.

**Comment by ro0NL** [comment]
> Unfortunately, feedback in this area is rare because most users don't use the PostalLabelFormatter.

:wave: assume this is used for eg. physical labels in international shipping ;)
